### ISSUE TITLE
static sharedElements function not being called on first mount

### ISSUE THREAD

**Issue by thijs-qv** [IjzerenHein/react-navigation-sharedelement#1]
I'm using a SwitchNavigator, which contains a TabNavigator, which contains a StackNavigator. I've wrapped the StackNavigator with the createSharedElementStackNavigator function. 

(I'm using react-navigation)

I have basically the same setup as the example in the Usage section:
An overview page, which contains a FlatList. The FlatList contains items, each item has an image which is wrapped with the SharedElement component.
A detail page, which contains a View with an image which is also wrapped with the SharedElement component.

The animations work great, except on the first mount of the detail page: no animation is shown when navigating to the detail page for the first time.

Putting a console.log in the static sharedElements function, which I've placed on the Detail screen, shows that it is not being called on the first mount. After it has been mounted every transition between the screens has the animation showing.

Any help would be greatly appreciated.

**Comment by IjzerenHein** [comment]
Hey Thijs, thanks for reporting this!
I think it's a due to a bug in the 0.4.4 version. Could you try downgrading to 0.4.3 and check whether the problem also occurs there?

**Comment by thijs-qv** [comment]
No worries, thanks for the quick reply.
I think you're right. I just downgraded to 0.4.3. and the animation is shown on the first mount as well.

**Comment by IjzerenHein** [comment]
Hey, I've fixed the problem and released it as 0.4.5

**Comment by IjzerenHein** [comment]
Haha, almost simultaneously :)
Yeah that's what I though. Well it should work with 0.4.5 now as well. Please use that version, it fixes some important stale/no-animation issues.
cheers!

**Comment by thijs-qv** [comment]
Nice. Thanks for the (incredibly) quick fix!
