### ISSUE TITLE
attempt to invoke virtual method android.graphics.rect.android.graphics.drawables.getbounds() on a null objaect reference

### ISSUE THREAD

**Issue by akramloginext** [IjzerenHein/react-navigation-sharedelement#281]
I'm having this error while navigating to details screen. I don't know why this error is occurring. It occurs any time while navigating to the details screen.   
Please help me on this issue. 

**This is my package.json .**

> @react-navigation/native": "^6.1.3",
> "@react-navigation/stack": "^6.3.12",
> "react-native": "^0.69.10",
> "react-native-shared-element": "^0.8.8",
> "react-navigation-shared-element": "^3.1.3", 

![Screenshot_1697037289](https://github.com/IjzerenHein/react-navigation-shared-element/assets/145097270/8b50c81c-8ada-4817-9c6b-0f30a396b078)

**Comment by akramloginext** [comment]
@p-syche 
I've fixed this issue by changing some native files in `react-native-shared-element` 

1. RNSharedElementDrawable.java

**Comment by akramloginext** [comment]
@p-syche 
I've fixed this issue by changing some native files in `react-native-shared-element` 

1. RNSharedElementDrawable.java

**Comment by akramloginext** [comment]
@p-syche 
I've fixed this issue by changing some native files in `react-native-shared-element` 

1. RNSharedElementDrawable.java
In this file I simply put an If condition in `drawReactImageView`  this method 
 ```
private void drawReactImageView(Canvas canvas) {
    // TODO FIX IMAGE STRETCH ISSUE WHEN IMAGE DOESN'T FILL
    // ENTIRE CANVAS
        ReactImageView imageView = (ReactImageView) mContent.view;
        RNSharedElementStyle style = mStyle;
        GenericDraweeHierarchy hierarchy = imageView.getHierarchy();
        Drawable drawable = hierarchy.getTopLevelDrawable();
    if (drawable != null) { // I added this condition 
      // Backup current props
        Rect oldBounds = new Rect(drawable.getBounds());
        ScaleType oldScaleType = hierarchy.getActualImageScaleType();
        RoundingParams oldRoundingParams = hierarchy.getRoundingParams();
        Drawable oldBackgroundImage = null; //hierarchy.getBackgroundImage();
        int oldFadeDuration = hierarchy.getFadeDuration();

        // Configure drawable
        drawable.setBounds(getBounds());
        hierarchy.setActualImageScaleType(style.scaleType);
        RoundingParams roundingParams = new RoundingParams();
        roundingParams.setBorderColor(style.borderColor);
        roundingParams.setBorderWidth(style.borderWidth);
        roundingParams.setRoundingMethod(RoundingParams.RoundingMethod.BITMAP_ONLY);
        roundingParams.setCornersRadii(
                style.borderTopLeftRadius,
                style.borderTopRightRadius,
                style.borderBottomRightRadius,
                style.borderBottomLeftRadius
        );
        hierarchy.setRoundingParams(roundingParams);
        hierarchy.setBackgroundImage(null);
        hierarchy.setFadeDuration(0);

        // Draw!
        drawable.draw(canvas);

        // Restore props
        hierarchy.setFadeDuration(oldFadeDuration);
        hierarchy.setBackgroundImage(oldBackgroundImage);
        hierarchy.setRoundingParams(oldRoundingParams);
        hierarchy.setActualImageScaleType(oldScaleType);
        drawable.setBounds(oldBounds);
    }
  }
```

similar issue we got in our google play console 
**Attempt to invoke virtual method 'void android.view.View.getLocationInWindow(int[])' on a null object reference**
For this also I made a small change in RNSharedElementTransition.java file in `react-native-shared-element`
previously it was something like this 
`View parent = (View) getParent();
    parent.getLocationInWindow(mParentOffset);`
then I made this 
` View parent = (View) getParent();
    if(parent == null){
      return;
    }
    parent.getLocationInWindow(mParentOffset);`

@p-syche   please let us know is this a right solution, and if it is if it can be merged into an official update. Thank you

**Comment by IjzerenHein** [comment]
@akramloginext Feel free to create a PR for that fix in https://github.com/IjzerenHein/react-native-shared-element 👍

**Comment by akramloginext** [comment]
@IjzerenHein I've created a PR in https://github.com/IjzerenHein/react-native-shared-element. Please let me know once reviewed.

**Comment by IjzerenHein** [comment]
Thanks @akramloginext ! I've merged your changes and released a new version of react-native-shared-element:
https://github.com/IjzerenHein/react-native-shared-element/releases/tag/v0.8.9
